'use client'

import Head from "next/head";

export default function NavButton() {

  async function login() {
    return
  }

  async function logout()  {

}






  return (
 <>

<Head>
        <title>Immutable Planner App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed flex justify-end px-4 gap-4 top-0 backdrop-blur-md py-4   w-full">
             <button className="text-grey-100 px-4 py-2 opacity-100 rounded-full bg-green-500 hover:bg-green-300" onClick={login}>
          Connect Passport
        </button>

        </div>


      </>


  );
}


