import Head from "next/head";
import InnerApp from "@/components/App";

export default function Home() {
  return (
    <>
      <Head>
        <title>Immutable App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mainApp">
        <InnerApp />
      </div>
    </>
  );
}

